services:
  scada-ui:
    build:
      context: .
      dockerfile: Dockerfile.cicd
      args:
        WWWGROUP: '${WWWGROUP}'
        APP_USER: '${APP_USER}'
    container_name: scada-ui
    image: scada-ui
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:8080'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=roadrunner --host=0.0.0.0 --rpc-port=6001 --port=80" 
    entrypoint: ["./entrypoint.sh"]
    networks:
      - sail

networks:
  sail:
    driver: bridge
